### ISSUE TITLE
NPM Error when running Docker Compose command

### ISSUE THREAD

**Issue by ifechi** [gscattolin/ExamSimulator#2]
Hello,

Encountered the error below while running `docker-compose up` command.

>  => ERROR [gui 5/6] RUN npm install                                                                                                                                                                                                   59.8s
 > [gui 5/6] RUN npm install:
59.67 npm ERR! code ERESOLVE
59.67 npm ERR! ERESOLVE could not resolve
59.67 npm ERR!
59.67 npm ERR! While resolving: react-scripts@5.0.1
59.67 npm ERR! Found: typescript@5.3.3
FROM node:latest as web-build
59.67 npm ERR! node_modules/typescript
59.67 npm ERR!   typescript@"^5.3.3" from the root project
59.67 npm ERR!
59.67 npm ERR! Could not resolve dependency:
59.67 npm ERR! peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
59.67 npm ERR! node_modules/react-scripts
59.67 npm ERR!   react-scripts@"^5.0.1" from the root project
59.67 npm ERR!
59.67 npm ERR! Conflicting peer dependency: typescript@4.9.5
59.67 npm ERR! node_modules/typescript
59.67 npm ERR!   peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
59.67 npm ERR!   node_modules/react-scripts
59.67 npm ERR!     react-scripts@"^5.0.1" from the root project
59.67 npm ERR!
59.67 npm ERR! Fix the upstream dependency conflict, or retry
59.67 npm ERR! this command with --force or --legacy-peer-deps
59.67 npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
59.67 npm ERR!
59.67 npm ERR!
59.67 npm ERR! For a full report see:
59.67 npm ERR! /root/.npm/_logs/2024-03-02T14_25_17_276Z-eresolve-report.txt
59.67
59.67 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-03-02T14_25_17_276Z-debug-0.log
------
> failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 1

**Comment by CK-Tex** [comment]
same error from my side as well

**Comment by gscattolin** [comment]
Updated solution.
